package Geo::TigerLine;

use strict;
use vars qw($VERSION);
$VERSION = '0.01';


=pod

=head1 NAME

Geo::TigerLine - TIGER/Line geographic data


=head1 DESCRIPTION

This is a module around the TIGER/Line geogrpahic data generated by
the U.S. Census.  TIGER/Line data files contain detailed information
about roads, waterways, political and property boundries, addresses,
etc...  Basically everything you need to recreate something like
Mapquest.

B<IT IS INCOMPLETE>


=head1 AUTHOR

Michael G Schwern <schwern@pobox.com>


=head1 COPYRIGHT

Copyright (c) 2000 Michael G Schwern

TIGER is a registered trademark of the US Census.


=head1 BUGS, CAVEATS and Other Musings

Seeing as how TIGER is trademarked, I might want to call this module
something else.


=head1 SEE ALSO

TIGER/Line data, manuals and additional info can
be gotten from ftp://ftp.linuxvc.com/US-map 

Bruce Perens's TIGER/Line mailing list is at
http://lists.perens.com/mailman/listinfo/map

=cut

return 'Mapquest must DIE!';
